#region License
//------------------------------------------------------------------------------ -
// Normcore-ParameterBinder
// https://github.com/chetu3319/Normcore-ParameterBinder
//------------------------------------------------------------------------------ -
// MIT License
//
// Copyright (c) 2022 Vishnu Sivan
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files(the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//------------------------------------------------------------------------------ -
#endregion
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RealtimeBoolModel
{
    [RealtimeProperty(1,true,true)]
    public bool _boolProperty;
}



/* ----- Begin Normal Autogenerated Code ----- */
public partial class RealtimeBoolModel : RealtimeModel {
    public bool boolProperty {
        get {
            return _boolPropertyProperty.value;
        }
        set {
            if (_boolPropertyProperty.value == value) return;
            _boolPropertyProperty.value = value;
            InvalidateReliableLength();
            FireBoolPropertyDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(RealtimeBoolModel model, T value);
    public event PropertyChangedHandler<bool> boolPropertyDidChange;
    
    public enum PropertyID : uint {
        BoolProperty = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _boolPropertyProperty;
    
    #endregion
    
    public RealtimeBoolModel() : base(null) {
        _boolPropertyProperty = new ReliableProperty<bool>(1, _boolProperty);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _boolPropertyProperty.UnsubscribeCallback();
    }
    
    private void FireBoolPropertyDidChange(bool value) {
        try {
            boolPropertyDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _boolPropertyProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _boolPropertyProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.BoolProperty: {
                    changed = _boolPropertyProperty.Read(stream, context);
                    if (changed) FireBoolPropertyDidChange(boolProperty);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _boolProperty = boolProperty;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
