#region License
//------------------------------------------------------------------------------ -
// Normcore-ParameterBinder
// https://github.com/chetu3319/Normcore-ParameterBinder
//------------------------------------------------------------------------------ -
// MIT License
//
// Copyright (c) 2022 Vishnu Sivan
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files(the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//------------------------------------------------------------------------------ -
#endregion
using Normal.Realtime;
using Normal.Realtime.Serialization;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[RealtimeModel]
public partial class RealtimeVector3Model
{
   [RealtimeProperty(1, true, true)] public Vector3 _vector3Property; 
}


/* ----- Begin Normal Autogenerated Code ----- */
public partial class RealtimeVector3Model : RealtimeModel {
    public UnityEngine.Vector3 vector3Property {
        get {
            return _vector3PropertyProperty.value;
        }
        set {
            if (_vector3PropertyProperty.value == value) return;
            _vector3PropertyProperty.value = value;
            InvalidateReliableLength();
            FireVector3PropertyDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(RealtimeVector3Model model, T value);
    public event PropertyChangedHandler<UnityEngine.Vector3> vector3PropertyDidChange;
    
    public enum PropertyID : uint {
        Vector3Property = 1,
    }
    
    #region Properties
    
    private ReliableProperty<UnityEngine.Vector3> _vector3PropertyProperty;
    
    #endregion
    
    public RealtimeVector3Model() : base(null) {
        _vector3PropertyProperty = new ReliableProperty<UnityEngine.Vector3>(1, _vector3Property);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _vector3PropertyProperty.UnsubscribeCallback();
    }
    
    private void FireVector3PropertyDidChange(UnityEngine.Vector3 value) {
        try {
            vector3PropertyDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _vector3PropertyProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _vector3PropertyProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Vector3Property: {
                    changed = _vector3PropertyProperty.Read(stream, context);
                    if (changed) FireVector3PropertyDidChange(vector3Property);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _vector3Property = vector3Property;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
