#region License
//------------------------------------------------------------------------------ -
// Normcore-ParameterBinder
// https://github.com/chetu3319/Normcore-ParameterBinder
//------------------------------------------------------------------------------ -
// MIT License
//
// Copyright (c) 2020 Andy Moore
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files(the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//------------------------------------------------------------------------------ -
#endregion
using Normal.Realtime;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RealtimeColorModel
{
    [RealtimeProperty(1,true,true)]
    public Color _colorProperty;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RealtimeColorModel : RealtimeModel {
    public UnityEngine.Color colorProperty {
        get {
            return _colorPropertyProperty.value;
        }
        set {
            if (_colorPropertyProperty.value == value) return;
            _colorPropertyProperty.value = value;
            InvalidateReliableLength();
            FireColorPropertyDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(RealtimeColorModel model, T value);
    public event PropertyChangedHandler<UnityEngine.Color> colorPropertyDidChange;
    
    public enum PropertyID : uint {
        ColorProperty = 1,
    }
    
    #region Properties
    
    private ReliableProperty<UnityEngine.Color> _colorPropertyProperty;
    
    #endregion
    
    public RealtimeColorModel() : base(null) {
        _colorPropertyProperty = new ReliableProperty<UnityEngine.Color>(1, _colorProperty);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _colorPropertyProperty.UnsubscribeCallback();
    }
    
    private void FireColorPropertyDidChange(UnityEngine.Color value) {
        try {
            colorPropertyDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _colorPropertyProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _colorPropertyProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.ColorProperty: {
                    changed = _colorPropertyProperty.Read(stream, context);
                    if (changed) FireColorPropertyDidChange(colorProperty);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _colorProperty = colorProperty;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
